### ISSUE TITLE
Slight woopsie in releases.json

### ISSUE THREAD

**Issue by bossanova808** [mmikkel/IncognitoField-Craft#2]
Think this was my woopsie - there's a missing comma between the two releases it seems, which gives a Craft.log error:

```
2016/07/13 00:19:27 [warning] [application] A “Incognito Field” release was skipped because it is invalid:
 - Missing required attributes (notes)
```

Should be ok to just fix the releases.json rather than do a full new release as Craft checks once a day.

And sorry!!

**Comment by bossanova808** [comment]
The date errors I am not immediately sure on, but the missing attributes one comes from the missing comma on line 24 - I used http://jsonlint.com/ to check it.

Thanks!

**Comment by mmikkel** [comment]
Hey @bossanova808 – no problem, I added the missing comma. Thanks for reporting + contributing!
